s = "hello world"
print(s.capitalize())
print(s.upper())
print(s.lower())
print(s.count("o"))
print(s.find("o"))
print(s.center(20, "z"))
"hello/thi".expandtabs()
s = "hello"
print(s.isalnum())
print(s.isalpha())
print(s.islower())
print(s.isspace())
print(s.istitle())
print(s.isupper())
print(s.endswith("o"))
print(s.split("e"))
s = "hihhiiihiiihihh"
print(s.split("i"))
print(s.partition("i"))